workflows:
  capacitor-ios-app-store:
    name: Capacitor iOS App Store Build
    instance_type: mac_mini_m2
    environment:
      groups:
        - app_store_credentials # Un gruppo sicuro per le nostre chiavi
      vars:
        APP_ID: "com.tuonome.colorswipeduel" # SOSTITUISCI CON IL TUO ID BUNDLE
    scripts:
      - name: Install npm dependencies
        script: | 
          npm install
      # --- RIGA AGGIUNTA PER RISOLVERE L'ERRORE ---
      - name: Set execute permissions for Capacitor CLI
        script: | 
          chmod +x ./node_modules/.bin/cap
      # --- FINE RIGA AGGIUNTA ---
      - name: Sync Capacitor project
        script: | 
          npx cap sync ios
      - name: Set up code signing
        script: | 
          app-store-connect fetch-signing-files "$APP_ID" --type IOS_APP_STORE --create
      - name: Build and archive iOS app
        script: | 
          xcode-project use-profiles
          xcode-project build-ipa --workspace "ios/App/App.xcworkspace" --scheme "App"
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID