workflows:
  capacitor-ios-app-store:
    name: Capacitor iOS App Store Build
    instance_type: mac_mini_m2
    environment:
      groups:
        - app_store_credentials 
      vars:
        APP_ID: "com.steexesimplegames.colorswipeduel" # SOSTITUISCI CON IL TUO ID BUNDLE
    scripts:
      - name: Install npm dependencies
        script: | 
          npm install
      - name: Set execute permissions for Capacitor CLI
        script: | 
          chmod +x ./node_modules/.bin/cap
      - name: Add and Sync Capacitor iOS platform
        script: | 
          npx cap add ios
          npx cap sync ios
      - name: Set up code signing
        script: | 
          app-store-connect fetch-signing-files "$APP_ID" --type IOS_APP_STORE --create
      - name: Build and archive iOS app
        script: | 
          xcode-project use-profiles
          xcode-project build-ipa --workspace "ios/App/App.xcworkspace" --scheme "App"
    artifacts:
      - build/ios/ipa/*.ipa
    # --- BLOCCO MODIFICATO: Usa i nomi corretti delle variabili ---
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
    # --- FINE BLOCCO MODIFICATO ---